"use client";
import Image from "next/image";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "../../components/Icons";
import { useAuth } from "../../lib/auth";

export default function RegisterPage(){
  const {register,user,loading}=useAuth(); const router=useRouter(); const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [show,setShow]=useState(false);
  useEffect(()=>{if(!loading&&user)router.replace("/dashboard")},[loading,user,router]);
  async function submit(e:FormEvent){e.preventDefault();setError("");if(password.length<8){setError("Password must contain at least 8 characters.");return}if(password!==confirm){setError("Passwords do not match.");return}setBusy(true);try{await register(name,email,password);router.replace("/dashboard")}catch(err:any){setError(err.message)}finally{setBusy(false)}}
  return <div className="auth-shell"><div className="auth-panel">
    <div className="auth-art"><Link href="/"><Image src="/quantuminsight-logo.png" alt="QuantumInsight" width={210} height={100} className="h-auto w-[190px] object-contain"/></Link><div className="mt-20"><div className="badge border-violet-400/20 bg-violet-400/5 text-violet-200">QHI · ML · Qiskit</div><h1 className="mt-5 text-4xl font-black leading-tight">Build better quantum circuits with a smarter feedback loop.</h1><p className="mt-5 max-w-md text-sm leading-6 text-slate-400">Create your account and unlock the full QuantumInsight workspace: analysis, debugging, optimization, anomaly signals and circuit history.</p><div className="mt-10 space-y-3">{["Six-factor Quantum Health Index","AI-style debugging recommendations","Optimization and circuit comparisons"].map(x=><div key={x} className="flex items-center gap-3 text-sm text-slate-300"><span className="grid h-6 w-6 place-items-center rounded-full bg-cyan-400/10 text-cyan-300"><Icon name="check" size={14}/></span>{x}</div>)}</div></div></div>
    <div className="auth-form"><div className="mx-auto max-w-md"><Link href="/" className="mb-8 block text-xs font-bold text-slate-500 hover:text-white">← Back to QuantumInsight</Link><p className="section-kicker">Get started</p><h2 className="mt-2 text-3xl font-black">Create your account</h2><p className="mt-2 text-sm text-slate-400">Start analyzing quantum circuits in a few seconds.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block"><span className="mb-2 block text-xs font-bold text-slate-300">Full name</span><input value={name} onChange={e=>setName(e.target.value)} required minLength={2} placeholder="Your name"/></label><label className="block"><span className="mb-2 block text-xs font-bold text-slate-300">Email address</span><input value={email} onChange={e=>setEmail(e.target.value)} required type="email" placeholder="you@example.com"/></label><label className="block"><span className="mb-2 block text-xs font-bold text-slate-300">Password</span><div className="relative"><input value={password} onChange={e=>setPassword(e.target.value)} required type={show?"text":"password"} minLength={8} placeholder="At least 8 characters" className="pr-14"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-slate-500">{show?"Hide":"Show"}</button></div></label><label className="block"><span className="mb-2 block text-xs font-bold text-slate-300">Confirm password</span><input value={confirm} onChange={e=>setConfirm(e.target.value)} required type={show?"text":"password"} placeholder="Repeat your password"/></label>{error&&<div className="rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</div>}<button disabled={busy} className="btn btn-primary w-full py-3.5">{busy?"Creating account…":"Create account"}<Icon name="arrow" size={16}/></button></form><p className="mt-6 text-center text-xs text-slate-500">Already have an account? <Link href="/login" className="font-bold text-cyan-300">Sign in</Link></p></div></div>
  </div></div>;
}
